# Generated by Django 5.0.4 on 2024-05-15 12:41

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='viagem',
            options={'verbose_name': 'Viagem', 'verbose_name_plural': 'Viagens'},
        ),
        migrations.AddField(
            model_name='viagem',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='aplicacao'),
        ),
        migrations.AlterField(
            model_name='viagem',
            name='criador',
            field=models.ForeignKey(default=django.contrib.auth.models.User, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='viagem',
            name='descricao',
            field=models.TextField(verbose_name='Descrição'),
        ),
    ]
