# Generated by Django 5.0.4 on 2024-05-15 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0002_alter_viagem_options_viagem_imagem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viagem',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='statics/assets/img-viagens'),
        ),
    ]
